name: Bug 回饋
description: 描述你所遇到的bug
labels: [ "bug" ]
title: "[Bug] "
body:

  - type: checkboxes
    id: checklist
    attributes:
      label: 檢查清單
      options:
        - label: 搜尋了 [歷史 issue](https://github.com/david082321/PiliPlus-zhTW/issues?q=is%3Aissue) ，並未發現相同問題
          required: true
        - label: 正在使用最新版本。
          required: true
        - label: 已排除網路問題
          required: true
        - label: 已排除帳號問題
          required: true
        - label: 已排除設定問題
          required: true
  
  - type: checkboxes
    id: assign
    attributes:
      label: Assign
      options:
        - label: self-assign
          required: false

  - type: textarea
    id: version
    attributes:
      label: 版本號
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 復現步驟
      description: 請提供復現該問題所需的具體步驟。
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 預期行為
      description: 請描述你期望的正確行為或結果。
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 實際行為
      description: 請描述實際的行為或結果。
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: 錯誤日誌
      description: 請提供設定->關於->錯誤日誌中的內容，貼上在下方程式碼框中。如果沒有，請提供您的app版本號、系統版本、裝置型號等相關資訊。

  - type: textarea
    id: info
    attributes:
      label: 相關資訊
      description: 請補充截圖、螢幕錄影、BV號等其他有助於解決問題的資訊。
